### ISSUE TITLE
One way only

### ISSUE THREAD

**Issue by hixair** [pgrimaud/lametric-slack#1]
Hi !
Do you plan on allowing messages posted to à slack channel to be displayed on LaMetric ?
Thx !

**Comment by pgrimaud** [comment]
Hello,

It's impossible because this is a "button" app.
Maybe, I will try to convert it to an "indicator app" which can receive messages.

**Comment by hixair** [comment]
I would love that !!
And sorry, I should have posted that as a feature request, not an issue !

**Comment by Fusty** [comment]
Indicator app would be much more useful!  But then again, I don't own one (yet).

**Comment by Walkeezy** [comment]
Indicator app would be fantastic!
