### ISSUE TITLE
getting the x after pressing the button

### ISSUE THREAD

**Issue by fitzgr** [pgrimaud/lametric-slack#2]
Pierre, here's a dump of the parms I'm using in the LaMetric Slack config. 

Name of Bot  
Slack Notifications  
#channel or @people  
#general  
Icon Emoji  
:sunglasses:  
Text message  
Hello world!  
Token (everything after the services/)  
T3CQA3JFM/B44L58XD6/8Cfe40YA8Tap2sJM5MPdoNZ7haR

Anything that appears obviously wrong? I've tried 2 LaMetrics, on difference networks, reinstalled the Slack app on LaMetric, but still getting the X.

**Comment by pgrimaud** [comment]
Hello,

I'm at work until 11pm and can't test my LaMetric now.

But did you create your token for the #general room ?

![hook](https://cloud.githubusercontent.com/assets/1866496/22935957/5b43b24a-f2d4-11e6-86fd-96e7b20c404a.png)

**Comment by fitzgr** [comment]
I hadn't, but recreated one for #general as per your picture. And only using the part after the services/
but still no go. Thanks for your support and I understand about the timing. This is what I'm using now
https://hooks.slack.com/services/
token below
T3CQA1FFM/B4KE643HC/A49vrVLKF6OWNfZsq8bzODG8

**Comment by pgrimaud** [comment]
@fitzgr Ok, I upgraded my server which hosts this application, a few days ago and I missed a package.

I just simulated the click, tell me if you can see the message on slack.

**Comment by fitzgr** [comment]
We see the message "Hello World" both yours, and when we press the button on LaMetric. SO the button press on LaMetric definitely works. And we get the "check box" response from the LaMetric". But when we send a #general message in Slack I was expecting to see it on LaMetric. Is there something that we need to reload as a result of the missed package?

**Comment by pgrimaud** [comment]
Glad to see it's fixed.
Unfortunately, the app can't read the messages from any room. Btw the redesign of this application is in my todo list.

**Comment by fitzgr** [comment]
@pgrimaud Thanks for clearing this one up. So what you're saying Pierre is the current function is  to send from the LaMetric button, the pre coded string in the LaMetric UI to the specified Slack channel (hence incoming webhooks)?

Ideally what would be nice is to have the LaMetric present the content on a configured Slack channel.

**Comment by pgrimaud** [comment]
@fitzgr Yes, the app post to the configured slack channel.

> Ideally what would be nice is to have the LaMetric present the content on a configured Slack channel.

I will add this functionality in the next version.

**Comment by lo5co** [comment]
It doesn't work anymore. I've reinstalled app, regenerated token but when I press the button I receive the X error.
