### ISSUE TITLE
LaMetric Outgoing WebHooks? Recv Slack notifications on LaMetric?

### ISSUE THREAD

**Issue by jax1111321** [pgrimaud/lametric-slack#5]
Is it possible to use this LaMetric Slack app to receive slack notifications via the Slack "Outgoing WebHooks"?

Please advise,

John Jackson
jax1111@gmail.com

**Comment by pgrimaud** [comment]
Hello @jax1111321,

You can take a look [here](https://bigyouth.slack.com/apps/A452R7K17-lametric) or [here](https://help.lametric.com/support/solutions/articles/6000170888-how-to-add-lametric-bot-to-any-channel-on-slack-). :)

Regards,
Pierre
